'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import TopBar from '../../components/shared/TopBar';
import Button from '../../components/shared/Button';
import ProgressBar from '../../components/shared/ProgressBar';
import CameraPill from '../../components/camera/CameraPill';
import useScanner from '../../components/scanner/useScanner';
const steps=[{icon:'⌗',title:'Set up eye control',text:'A quick check tunes blinking to your eyes and lighting. Tap Start and follow along — it takes about ten seconds.',intro:true},{icon:'▣',title:'Starting camera…',text:'One moment — getting eye control ready. Allow the camera if your browser asks.',value:14},{icon:'◉',title:'Keep your eyes open',text:'Look at the screen, relaxed.',value:38},{icon:'◉',title:'Get ready…',text:'When you hear the beep, close your eyes and hold them shut.',value:60},{icon:'◉̸',title:'Close your eyes now',text:'Hold them shut until you hear the next tone.',value:82}];
export default function Setup(){const router=useRouter(),[step,setStep]=useState(0),[eye,setEye]=useState(true);const next=()=>step===steps.length-1?router.push('/home'):setStep(x=>x+1);const {select}=useScanner([{label:step===0?'Start':'Continue'}],next);const blink=useRef(select);blink.current=select;const onBlink=useCallback(()=>blink.current(),[]);useEffect(()=>{if(step&&step<steps.length){const id=setTimeout(next,step===1?1600:2600);return()=>clearTimeout(id)}},[step]);const current=steps[step];return <main className="app"><TopBar eyeOn={eye} toggleEye={()=>setEye(x=>!x)} onHelp={()=>router.push('/')}/><div className="screen-center"><section className="calibration"><div className="cal-icon">{current.icon}</div><h1>{current.title}</h1><p>{current.text}</p>{current.intro?<div className="button-row"><Button className="primary" onSelect={()=>select(0)}>Start</Button><Button onSelect={()=>router.push('/home')}>Skip for now</Button></div>:<ProgressBar value={current.value}/>}</section></div><CameraPill enabled={eye} onLongBlink={onBlink}/></main>}
