'use client';
import { useEffect, useRef, useState } from 'react';
// MediaPipe stays isolated here. CPU detection avoids fragile WebGL texture uploads on webcams.
export default function CameraPill({ enabled, onLongBlink }) {
  const video = useRef(null), [status,setStatus] = useState(enabled ? 'Starting camera…' : 'Eye control is off'), closed = useRef(0), sent = useRef(false);
  useEffect(() => { let stream, landmarker, frame, cancelled=false; if (!enabled) { setStatus('Eye control is off'); return; }
    (async () => { try { stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'}}); if(cancelled)return; video.current.srcObject=stream; await video.current.play(); const vision=await import(/* webpackIgnore: true */ 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/+esm'); const fileset=await vision.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm'); landmarker=await vision.FaceLandmarker.createFromOptions(fileset,{baseOptions:{delegate:'CPU',modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/latest/face_landmarker.task'},runningMode:'VIDEO',numFaces:1}); const tick=()=>{if(cancelled)return;if(!video.current?.videoWidth||video.current.readyState<2){frame=requestAnimationFrame(tick);return}const r=landmarker.detectForVideo(video.current,performance.now()),p=r.faceLandmarks?.[0];if(!p){setStatus('Face not detected — click or press Space');frame=requestAnimationFrame(tick);return}const gap=(p[159].y-p[145].y+p[386].y-p[374].y)/2,isClosed=gap<.008;setStatus(isClosed?'Long blink to select…':'Tracking your eyes');if(isClosed){closed.current ||= performance.now();if(performance.now()-closed.current>700&&!sent.current){sent.current=true;onLongBlink()}}else{closed.current=0;sent.current=false}frame=requestAnimationFrame(tick)};tick()}catch{setStatus('Camera unavailable — click or press Space')}})();
    return ()=>{cancelled=true;cancelAnimationFrame(frame);landmarker?.close?.();stream?.getTracks().forEach(t=>t.stop())}; },[enabled,onLongBlink]);
  return <aside className="camera" aria-live="polite">{enabled?<><video ref={video} muted playsInline/><div className="camera-label"><b>•</b> {status}</div></>:<div className="camera-off">{status}<br/>Click or press Space to select</div>}</aside>;
}
